spring.application.name=inventory
# 1. Where does the database live?
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db

# 2. Your PostgreSQL username (default is postgres)
spring.datasource.username=postgres

# 3. Your PostgreSQL password (REPLACE THIS WITH YOUR ACTUAL PASSWORD)
spring.datasource.password=SyEd@#1346

# 4. The Magic: Tell Java to automatically create our SQL tables for us
spring.jpa.hibernate.ddl-auto=update

# 5. Show us the SQL in the console so we can see it working
spring.jpa.show-sql=true